fix console error by reversing jquery version
"Uncaught TypeError: e.indexOf is not a function"
mistake: I updated jquery 2.1.0 to 3.6.1 before minification,
didn't write it in the corresponding commit 0f6fd72,
pushed the change,
and the error appeared in the lighthouse report;
fix: reverse to jquery 2.1.0